name: FamilyNovaKids
options:
  bundleIdPrefix: com.familynova
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "14.0"

packages: {}

targets:
  FamilyNovaKids:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: FamilyNovaKids
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.familynova.kids
      PRODUCT_NAME: FamilyNovaKids
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: "" # Set your Apple Developer Team ID here (e.g., "ABC123XYZ")
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Nova
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - familynovakids
              - familynova-kids

