name: FamilyNovaParent
options:
  bundleIdPrefix: com.familynova
  deploymentTarget:
    iOS: "15.0"
  developmentLanguage: en
  xcodeVersion: "14.0"

packages: {}

targets:
  FamilyNovaParent:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: FamilyNovaParent
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.familynova.parent
      PRODUCT_NAME: FamilyNovaParent
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.7"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: FamilyNova Parent
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true

